services:
  db:
    image: pgvector/pgvector:pg17
    container_name: pgvector-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: example_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./postgres/schema.sql:/docker-entrypoint-initdb.d/schema.sql

  n8n:
    image: docker.n8n.io/n8nio/n8n
    container_name: n8n_app
    ports:
      - "5678:5678"
    environment:
      N8N_BLOCK_FILE_ACCESS_TO_N8N_FILES: false
      DB_TYPE: postgresdb
      DB_POSTGRESDB_HOST: db
      DB_POSTGRESDB_PORT: 5432
      DB_POSTGRESDB_DATABASE: example_db
      DB_POSTGRESDB_USER: postgres
      DB_POSTGRESDB_PASSWORD: password
    volumes:
      - n8n_data:/home/node/.n8n
      - ./documents:/tmp/documents
    depends_on:
      - db

volumes:
  pgdata:
  n8n_data: